from pathlib import Path
import re,ast,json,sys
ROOT=Path(__file__).resolve().parents[1]
s=(ROOT/'solver7_search.c').read_text()
def mat(name):
 x=re.search(r'\b'+name+r'\[3\]\[3\]\[CUBIES\] = (.*?);',s,re.S).group(1)
 return ast.literal_eval(x.replace('{','[').replace('}',']'))
source=mat('move_source');twist=mat('move_twist')
def turn(st,m):
 f,t=divmod(m,3);p,o=st
 return tuple(p[j] for j in source[f][t]),tuple((o[j]+d)%3 for j,d in zip(source[f][t],twist[f][t]))
sol=(tuple(range(7)),(0,)*7)
canon={sol:()}; levels=[[((),sol)]]
for n in range(1,6):
 layer=[]; bad=0
 for w,st in levels[-1]:
  for m in range(9):
   if w and w[-1]//3==m//3:continue
   v=w+(m,); ns=turn(st,m)
   if ns not in canon:canon[ns]=v
   if canon[ns]!=v:bad+=1
   layer.append((v,ns))
 levels.append(layer)
 print(n,len(layer),bad,len(canon),file=sys.stderr)
# Full base9 prefix indices, byte bitmask over six legal continuations.
h=[]; stats={}
for n in range(3,6):
 arr=[0]*(9**(n-1)); bad=0
 for w,st in levels[n]:
  if canon[st]==w:continue
  prefix=w[:-1]; ix=0
  for m in prefix:ix=ix*9+m
  m=w[-1]; face=prefix[-1]//3
  bit=m if m<face*3 else m-3
  arr[ix]|=1<<bit;bad+=1
 h.append('static const unsigned char sequence_reject%d[%d] = {\n%s\n};'%(n,len(arr),',\n'.join(','.join(map(str,arr[i:i+32])) for i in range(0,len(arr),32))))
 stats[n]={'bytes':len(arr),'forbidden':bad,'nonzero':sum(bool(x) for x in arr)}
print('/* Generated by tools/generate_solver7_search_sequences.py; 7371 table bytes. */')
print('\n'.join(h))
print('/* moves[0..depth-1] are 1..9, and must already have survived pruning.\n * Compute once on entering a node; cache until that node is exhausted.\n * A set bit m rejects move m+1, including all same-face continuations.\n */\nstatic unsigned sequence_forbidden(const int *moves, int depth)\n{\n    if (!depth) return 0;\n    int last = moves[depth - 1] - 1;\n    int shift = last < 3 ? 0 : (last < 6 ? 3 : 6);\n    unsigned forbidden = 7U << shift;\n    if (depth < 2) return forbidden;\n    int length = depth < 4 ? depth : 4;\n    int index = 0;\n    for (int i = depth - length; i < depth; ++i)\n        index = (index << 3) + index + moves[i] - 1;\n    unsigned byte = length == 2 ? sequence_reject3[index] :\n                    length == 3 ? sequence_reject4[index] :\n                                  sequence_reject5[index];\n    unsigned low = (1U << shift) - 1;\n    return forbidden | (byte & low) | ((byte & ~low) << 3);\n}\n')
