/* AI-assisted host generator: abstract distances only, not full cube distances. */
#include <stdio.h>
#include <assert.h>
#define SOLVER4_HOST_TEST
#include "../solver4.c"
void solver4_host_putc(int c) { (void)c; }
static uint8_t sparse[117649];
/* Emit six-dimensional initialization without recursion. */
static void emit(const char *name, int radix, const uint8_t *values, int count)
{
    printf("static const uint8_t %s", name);
    for (int i = 0; i < 6; ++i) printf("[%d]", radix);
    puts(" = {");
    for (int i = 0; i < count; ++i) {
        int stride = count / radix;
        for (int level = 0; level < 5; ++level) {
            if (i % stride == 0) putchar('{');
            stride /= radix;
        }
        printf("%u,", values[i]);
        stride = radix;
        for (int level = 0; level < 5; ++level) {
            if ((i + 1) % stride == 0) printf("},");
            stride *= radix;
        }
        if ((i + 1) % radix == 0) putchar('\n');
    }
    puts("};");
}
int main(void)
{
    init_heuristic();
    for (int i = 0; i < 117649; ++i) sparse[i] = UINT8_MAX;
    for (int r = 0; r < PERMUTATIONS; ++r) {
        state_t s = abstract_state(r, 0);
        int key = 0;
        for (int i = 0; i < 6; ++i) key = key * 7 + s.p[i];
        assert(sparse[key] == UINT8_MAX && perm_dist[r] != UINT8_MAX);
        sparse[key] = perm_dist[r];
    }
    for (int r = 0; r < ORIENTATIONS; ++r) assert(orient_dist[r] != UINT8_MAX);
    puts("/* Generated by tools/generate_solver7_tables.c; invalid permutation slots are 255. */");
    emit("perm_dist", 7, sparse, 117649);
    emit("orient_dist", 3, orient_dist, ORIENTATIONS);
    return ferror(stdout) ? 1 : 0;
}
