/* AI-assisted host utility; emits abstract transitions, not full-cube distances. */
#include <stdio.h>
#define SOLVER4_HOST_TEST
#include "../solver4.c"
void solver4_host_putc(int c) { (void)c; }
int main(void)
{
    puts("/* Generated by tools/generate_solver5_tables.c. Do not edit. */");
    puts("_Static_assert(sizeof(unsigned short) == 2, \"16-bit table entries required\");");
    for (int kind = 0; kind < 2; ++kind) {
        int count = kind ? ORIENTATIONS : PERMUTATIONS;
        printf("static const unsigned short %s_transition[%d][MOVES] = {\n",
               kind ? "orient" : "perm", count);
        for (int rank = 0; rank < count; ++rank) {
            state_t state = abstract_state(rank, kind);
            printf("    {");
            for (int move = 0; move < MOVES; ++move) {
                state_t next;
                uint8_t face = move_face((uint8_t)move);
                apply_move(&state, &next, face, move_turns((uint8_t)move, face));
                printf("%s%d", move ? "," : "",
                       kind ? orientation_index(&next) : permutation_index(&next));
            }
            puts("},");
        }
        puts("};");
    }
    return ferror(stdout) ? 1 : 0;
}
